[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kalman-filter"
version = "0.1.1"
description = "Simple Kalman filter implementation."
requires-python = ">=3.11"  # needed for later versiono of Pandas
dependencies = [
  "pandas"  # will install numpy as its depenancy
]
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
    "jupyter",
    "ipykernel"
]